import { GoogleGenerativeAI } from '@google/generative-ai';
import { getPrompt, type Country } from './prompts';

const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || '');

// Imagen 3 model for image generation
const imageModel = genAI.getGenerativeModel({ model: 'gemini-2.5-flash-image' });

export interface GeneratedRecipe {
  title: string;
  prepTime: number;
  cookTime: number;
  ingredients: string[];
  instructions: string[];
  difficulty: 'easy' | 'medium' | 'hard';
  servings?: number;
  country: string;
  language: string;
}

export class GeminiService {
  private model;

  constructor(modelName: string = 'gemini-2.5-flash') {
    if (!process.env.GEMINI_API_KEY) {
      throw new Error('GEMINI_API_KEY is not set in environment variables');
    }
    this.model = genAI.getGenerativeModel({ model: modelName });
  }

  async generateRecipe(ingredients?: string[], country: Country = 'argentina', language: string = 'es', existingTitles?: string[]): Promise<GeneratedRecipe> {
    const prompt = getPrompt(country, ingredients, existingTitles);
    
    try {
      const result = await this.model.generateContent(prompt);
      const response = await result.response;
      const text = response.text();
      
      // Parse the JSON response
      const recipe = this.parseRecipeResponse(text);
      return {
        ...recipe,
        country,
        language,
      };
    } catch (error) {
      console.error('Error generating recipe with Gemini:', error);
      throw new Error('Failed to generate recipe');
    }
  }

  private parseRecipeResponse(text: string): Omit<GeneratedRecipe, 'country' | 'language'> {
    // Remove markdown code blocks if present
    let cleanedText = text.trim();
    if (cleanedText.startsWith('```')) {
      cleanedText = cleanedText.replace(/^```(?:json)?\n?/i, '').replace(/\n?```$/i, '');
    }
    
    try {
      const parsed = JSON.parse(cleanedText);
      
      // Validate structure
      if (!parsed.title || !parsed.ingredients || !parsed.instructions) {
        throw new Error('Invalid recipe structure');
      }
      
      // Ensure difficulty is valid
      const validDifficulties = ['easy', 'medium', 'hard'];
      if (!validDifficulties.includes(parsed.difficulty)) {
        parsed.difficulty = 'medium';
      }
      
      // Validate servings if present
      let servings: number | undefined = undefined;
      if (parsed.servings !== undefined && parsed.servings !== null) {
        const servingsNum = typeof parsed.servings === 'number' ? parsed.servings : parseInt(parsed.servings, 10);
        if (!isNaN(servingsNum) && servingsNum >= 1 && servingsNum <= 12) {
          servings = servingsNum;
        }
      }
      
      // Extract prepTime, cookTime with defaults
      const prepTime = typeof parsed.prepTime === 'number' ? parsed.prepTime : 15;
      const cookTime = typeof parsed.cookTime === 'number' ? parsed.cookTime : 30;
      
      return {
        title: parsed.title,
        prepTime,
        cookTime,
        ingredients: Array.isArray(parsed.ingredients) ? parsed.ingredients : [],
        instructions: Array.isArray(parsed.instructions) ? parsed.instructions : [],
        difficulty: parsed.difficulty,
        ...(servings !== undefined && { servings }),
      };
    } catch (error) {
      console.error('Error parsing Gemini response:', error);
      console.error('Response text:', text);
      throw new Error('Failed to parse recipe response');
    }
  }

  /**
   * Generate an image for a recipe using Imagen 3
   * @param title - Recipe title
   * @param ingredients - List of main ingredients
   * @param country - Country cuisine
   * @returns Buffer containing the generated image
   */
  async generateRecipeImage(title: string, ingredients: string[], country: string): Promise<Buffer> {
    // Build a detailed prompt for food photography
    const mainIngredients = ingredients.slice(0, 5).join(', ');
    
    const prompt = `Professional food photography of ${title}, a traditional ${country} cuisine dish. 
The image should show: ${mainIngredients}. 
Style: High quality food photography, well-lit, appetizing presentation, restaurant quality plating, 
shallow depth of field, warm natural lighting, 1024x768 landscape format.
Requirements: Web-optimized, lightweight, suitable for recipe card display, no text or watermarks.`;

    try {
      console.log(`🎨 Generating image for: ${title}`);
      console.log(`📝 Prompt: ${prompt.substring(0, 100)}...`);

      // Imagen 3 expects a string prompt, not an object
      const result = await imageModel.generateContent(prompt);

      const response = await result.response;
      
      // Get the image data from the response
      // Imagen 3 returns images as base64 encoded strings in the response
      if (!response || !response.candidates || response.candidates.length === 0) {
        throw new Error('No image generated by Imagen 3');
      }

      const candidate = response.candidates[0];
      
      // Extract image data - Imagen 3 returns images in different formats
      // Check for inline data or file data
      let imageData: string | undefined;
      
      if (candidate.content?.parts) {
        for (const part of candidate.content.parts) {
          if (part.inlineData?.data) {
            imageData = part.inlineData.data;
            break;
          }
        }
      }

      if (!imageData) {
        throw new Error('No image data found in Imagen 3 response');
      }

      // Convert base64 to buffer
      const buffer = Buffer.from(imageData, 'base64');
      
      console.log(`✅ Image generated successfully, size: ${(buffer.length / 1024).toFixed(2)}KB`);
      
      return buffer;
    } catch (error) {
      console.error('❌ Error generating image with Imagen 3:', error);
      throw new Error(`Failed to generate recipe image: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }
}
